filhodanuvem/awesome-php-jobs

README.md

Add a few new companies

---

README.md

* Folha de São Paulo
* OLX
* Automattic

Add new companies

---

README.md

Two additional huge companies working with PHP =)

Add Cloudfare + Etsy

---

README.md

Add more companies

---

README.md

Add PicPay

---

README.md

- I've added:
> Altran
> Bold
> PrimeIt
> SmartConsulting

Some Portuguese companies that use PHP

---

README.md

Add Page Personnel company that has a job for PHP.

Add Page Personnel

---

README.md

Add Pipe Run

---

README.md

Cheers,
I've added: Altran, Tequila Rapido and Zizoo.
=)

Add some companies

---

README.md

Hi, I'm adding the company that I work for.

Add Sysvale to the List

---

README.md

Added PetiKo

---

README.md

Adicionando empresas sergipanas

---

README.md

Sorry, but I should have done this in the previous PR to avoid having two different ones.
Either way, I've done a small research to include companies that I know could fit :-)
PS: This PR adds 5 new companies to the list.

Added a few more companies

---

README.md

Finalmente comecei a criar coragem para contribuir com a comunidade, sempre me senti inseguro com isso por achar que não sei o suficiente, porém decidi começar por algo super simples e básico, mas que sei que pode ajudar alguém em algum momento. Espero poder contribuir de outras maneiras e continuar evoluindo.

Adicionado algumas empresas com sede em Brasília Brasil

---

README.md

Adicionei as 3 últimas empresas que trabalhei com PHP na lista: Ezoom (Brasil), SomosGAD (Argentina) e Lendflow (EUA)

Adicionei 3 empresas em que trabalhei com PHP

---

README.md

added company Blockbit from São Paulo, Brazil.

added company

---

README.md

Olá!
Adicionando algumas empresas que vi na thread do [pokemao](https://twitter.com/pokemaobr/status/1354504035122950144) e que notei que  não estavam listadas aqui.
Como esse é um dos primeiros PR's que realizei, agradeço a paciência devido ao ultimo PR que fiz.

Add empresas não listadas

---

README.md

Adicionando Convenia

---

README.md

Add Live eCommerce to the list

Add Live eCommerce

---

README.md

Spreaker is a platform for creating, hosting, distributing, and monetizing your podcasts. PHP powers the APIs behind the site and the cms

Adds Spreaker
